import { Component } from '@angular/core';
import { Table, TableColumn } from '@shared/component/table/table';

@Component({
  selector: 'app-user-management',
  imports: [Table],
  templateUrl: './user-management.html',
  styleUrl: './user-management.css',
})
export class UserManagement {
  columns: TableColumn[] = [
    { field: 'id', header: 'No.', headerClass: 'w-14' },

    {
      field: 'fullName',
      header: 'Full Name',
      headerClass: 'min-w-[180px]',
      bodyClass: 'font-medium text-gray-700',
    },

    {
      field: 'mobile',
      header: 'Mobile No',
      headerClass: 'min-w-[140px]',
    },

    {
      field: 'email',
      header: 'Email',
      headerClass: 'min-w-[220px]',
    },

    {
      field: 'username',
      header: 'Username',
      headerClass: 'min-w-[140px]',
    },

    {
      field: 'birthdate',
      header: 'Birthdate',
      type: 'date',
      dateFormat: 'dd/MM/yyyy',
    },

    {
      field: 'gender',
      header: 'Gender',
      headerClass: 'min-w-[100px]',
    },

    {
      field: 'area',
      header: 'Area',
      headerClass: 'min-w-[150px]',
    },
    {
      field: 'city',
      header: 'City',
      headerClass: 'min-w-[150px]',
    },

    {
      field: 'state',
      header: 'State',
      headerClass: 'min-w-[150px]',
    },

    {
      field: 'status',
      header: 'Status',
      type: 'badge',
      badgeMap: {
        Active: 'border-green-200 bg-green-50 text-green-700',
        Inactive: 'border-red-200 bg-red-50 text-red-700',
      },
    },
  ];

  data = [
    {
      id: 1,
      fullName: 'Rahul Sharma',
      mobile: '9876543210',
      email: 'rahul.sharma@gmail.com',
      username: 'rahul123',
      birthdate: '1998-05-12',
      gender: 'Male',
      area: 'Satellite',
      state: 'Gujarat',
      city: 'Ahmedabad',
      status: 'Active',
    },
    {
      id: 2,
      fullName: 'Priya Patel',
      mobile: '9876543211',
      email: 'priya.patel@gmail.com',
      username: 'priya21',
      birthdate: '2000-03-22',
      gender: 'Female',
      area: 'Navrangpura',
      state: 'Gujarat',
      city: 'Ahmedabad',
      status: 'Inactive',
    },
    {
      id: 3,
      fullName: 'Amit Verma',
      mobile: '9876543212',
      email: 'amit.verma@gmail.com',
      username: 'amitv',
      birthdate: '1995-09-10',
      gender: 'Male',
      area: 'Bopal',
      state: 'Gujarat',
      city: 'Ahmedabad',
      status: 'Active',
    },
    {
      id: 4,
      fullName: 'Neha Gupta',
      mobile: '9876543213',
      email: 'neha.gupta@gmail.com',
      username: 'nehag',
      birthdate: '1999-11-03',
      gender: 'Female',
      area: 'Vastrapur',
      state: 'Gujarat',
      city: 'Ahmedabad',
      status: 'Active',
    },
    {
      id: 5,
      fullName: 'Karan Singh',
      mobile: '9876543214',
      email: 'karan.singh@gmail.com',
      username: 'karan_s',
      birthdate: '1997-02-15',
      gender: 'Male',
      area: 'Maninagar',
      state: 'Gujarat',
      city: 'Ahmedabad',
      status: 'Inactive',
    },
    {
      id: 6,
      fullName: 'Anjali Mehta',
      mobile: '9876543215',
      email: 'anjali.mehta@gmail.com',
      username: 'anjali_m',
      birthdate: '2001-06-20',
      gender: 'Female',
      area: 'Prahlad Nagar',
      state: 'Gujarat',
      city: 'Ahmedabad',
      status: 'Active',
    },
    {
      id: 7,
      fullName: 'Rohit Yadav',
      mobile: '9876543216',
      email: 'rohit.yadav@gmail.com',
      username: 'rohit_y',
      birthdate: '1996-08-17',
      gender: 'Male',
      area: 'Chandkheda',
      state: 'Gujarat',
      city: 'Ahmedabad',
      status: 'Active',
    },
    {
      id: 8,
      fullName: 'Pooja Shah',
      mobile: '9876543217',
      email: 'pooja.shah@gmail.com',
      username: 'pooja_s',
      birthdate: '1998-01-25',
      gender: 'Female',
      area: 'Gota',
      state: 'Gujarat',
      city: 'Ahmedabad',
      status: 'Inactive',
    },
    {
      id: 9,
      fullName: 'Vikas Kumar',
      mobile: '9876543218',
      email: 'vikas.kumar@gmail.com',
      username: 'vikas_k',
      birthdate: '1994-12-05',
      gender: 'Male',
      area: 'Naranpura',
      state: 'Gujarat',
      city: 'Ahmedabad',
      status: 'Active',
    },
    {
      id: 10,
      fullName: 'Sneha Joshi',
      mobile: '9876543219',
      email: 'sneha.joshi@gmail.com',
      username: 'sneha_j',
      birthdate: '2000-04-18',
      gender: 'Female',
      area: 'Thaltej',
      state: 'Gujarat',
      city: 'Ahmedabad',
      status: 'Active',
    },
    {
      id: 11,
      fullName: 'Arjun Patel',
      mobile: '9876543220',
      email: 'arjun.patel@gmail.com',
      username: 'arjun_p',
      birthdate: '1997-07-09',
      gender: 'Male',
      area: 'Iskcon',
      state: 'Gujarat',
      city: 'Ahmedabad',
      status: 'Inactive',
    },
    {
      id: 12,
      fullName: 'Riya Desai',
      mobile: '9876543221',
      email: 'riya.desai@gmail.com',
      username: 'riya_d',
      birthdate: '2002-10-30',
      gender: 'Female',
      area: 'Memnagar',
      state: 'Gujarat',
      city: 'Ahmedabad',
      status: 'Active',
    },
  ];
}
